### ISSUE TITLE
Expectations not compatible with Backbone Pagination

### ISSUE THREAD

**Issue by ahuth** [mavenlink/brainstem-js#55]
When using expectations in tests, the resulting Backbone Collection does not get the correct `state` object, which includes `totalRecords` and `totalPages`.

After running `expectation.respond()`, the `totalRecords` is `undefined`.

Some of our specs manually set `state.totalRecords = someNumber`, but this value gets over-ridden once the expectation responds.

I looked for a couple hours between yesterday and today through the expectation source, but could not figure out how to get this to work. Looks like a Collection's `state` object comes from the Pagination plugin, but it's not clear how it assigns the `state` data.

**Comment by cantino** [comment]
This would be worth fixing.  @jrolfs, whatcha think?

**Comment by jrolfs** [comment]
Yep, those specs with workarounds were admittedly me dodging this one. I'll take a crack at it.

**Comment by ahuth** [comment]
Jamie and I actually discussed this early in the week, and he shed a lot of light on the issue.

Seems that we need to implement `getServerCount` in the collection that ends up getting the response from the expectation.

**Comment by jrolfs** [comment]
So I've dug into this pretty deeply and haven't really come up with a clean way to implement the server count. Should it default to the length of the mocked response? It seems to me if you're writing specs for something that involves `getServerCount` then you can just mock out that method to return the count you need in yourj spec. I'm not sure implementing that in the expectation system is really worth it.

**Comment by cantino** [comment]
Defaulting to the length of the mocked response with an easy override seems fine, or whatever is easiest for now.

---
Andrew Cantino
Chief Architect, Mavenlink

**Comment by jrolfs** [comment]
Alright, I changed my mind: https://github.com/mavenlink/brainstem-js/pull/56. Let me know what you think over there.

**Comment by ahuth** [comment]
Looks good, and thanks for working on this.

Closing.
