### ISSUE TITLE
Cache key should include `includes`

### ISSUE THREAD

**Issue by juanca** [mavenlink/brainstem-js#68]
Seems like the computed cache key is missing `includes` which I feel would produce undesirable results.

https://github.com/mavenlink/brainstem-js/blob/444a840a7023e18556f90b7892fdd83b6e33efcf/vendor/assets/javascripts/brainstem/loaders/abstract-loader.coffee#L166-L179

e.g.

- Load a collection without any includes
- Reload the collection (same filters and what-have-yous) with some includes (possible as another part of the application)
  - Storage manager would utilize the cached response which is missing associated models

**Comment by juanca** [comment]
@jrolfs Whattya think?

**Comment by cantino** [comment]
I think we had a method that checks includes separately after fetching from
the cache? dependenciesLoaded or something?

Also: hi!

**Comment by jrolfs** [comment]
I think Andrew may be right, however that logic can be quite ... dense. It's definitely worth investigating and if it doesn't handle this case then I think we should add this.

**Comment by juanca** [comment]
Sounds good to me. Glad I posted this instead of just hacking away :D


P.S. Hello!

**Comment by juanca** [comment]
Investigated: legit. 

It only uses the cached response if and only if each model has the "loaded" associations cached -- it only cares when the model has the association key on its attributes. 


Here's the flow for the sake of information:

`AbstractLoader#_checkCacheForData` 
`BrainstemModel#dependenciesAreLoaded`
`BrainstemModel#associationsAreLoaded` & `BrainstemModel#optionalFieldsAreLoaded`

So it's good! Closing this issue.
